---
- hosts: webserver
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - name: ">> 1. Basic Server Setup & Dependencies"
      apt:
        name: ['ufw','curl','git']
        state: present
        update_cache: yes

    - name: ">> 2. Configure Firewall"
      ufw:
        rule: allow
        port: "{{ item }}"
      loop: ['22','80','443']

    - name: ">> 3. Install Docker"
      block:
        - name: "Create directory for apt keyrings"
          file: { path: /etc/apt/keyrings, state: directory, mode: '0755' }
        - name: "Download Docker's GPG key"
          shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
          args: { creates: /etc/apt/keyrings/docker.gpg }
        - name: "Add Docker repository"
          apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
            state: present
        - name: "Install Docker packages"
          apt:
            name: ['docker-ce','docker-ce-cli','containerd.io','docker-compose-plugin']
            state: present
            update_cache: yes
        - name: "Add '{{ server_user }}' to docker group"
          user: { name: "{{ server_user }}", groups: docker, append: yes }

    - name: ">> 4. Setup Project Structure & Configs"
      become_user: "{{ server_user }}"
      block:
        - name: "Create project directories"
          file:
            path: "{{ project_path }}/{{ item }}"
            state: directory
          loop: ['','src','nginx']
        - name: "Template out Docker files"
          template:
            src: "templates/{{ item.src }}"
            dest: "{{ project_path }}/{{ item.dest }}"
          loop:
            - { src: 'docker-compose.yml.j2', dest: 'docker-compose.yml' }
            - { src: 'Dockerfile.j2', dest: 'Dockerfile' }
            - { src: 'nginx.conf.j2', dest: 'nginx/default.conf' }

    - name: ">> 5. Install Laravel via Docker"
      block:
        - name: "Install Laravel using a temporary Composer container"
          command: >
            docker run --rm -v "{{ project_path }}/src:/app" composer create-project --prefer-dist laravel/laravel .
          args:
            creates: "{{ project_path }}/src/artisan"

    - name: ">> 6. Configure Permissions & Finalize Laravel"
      block:
        - name: "Set project ownership to web user"
          file: { path: "{{ project_path }}", owner: "{{ server_user }}", group: "www-data", recurse: yes }
        - name: "Set writable permissions for storage and cache"
          file: { path: "{{ project_path }}/src/{{ item }}", state: directory, mode: 'g+w', recurse: yes }
          loop: ['storage','bootstrap/cache']
        - name: "Set permissions for .env to be writable"
          file: { path: "{{ project_path }}/src/.env", mode: '0664' }
        - name: "Set database credentials in Laravel .env"
          lineinfile:
            dest: "{{ project_path }}/src/.env"
            regexp: "^{{ item.key }}="
            line: "{{ item.key }}={{ item.value }}"
          loop:
            - { key: 'DB_HOST', value: 'db' }
            - { key: 'DB_DATABASE', value: '{{ db_name }}' }
            - { key: 'DB_USERNAME', value: '{{ db_user }}' }
            - { key: 'DB_PASSWORD', value: '{{ db_password }}' }
            - { key: 'APP_URL', value: 'https://{{ domain_name }}' }

    - name: ">> 7. Obtain SSL Certificate"
      block:
        - name: "Run Certbot to get certificate"
          command: >
            docker run --rm -p 80:80
            -v "/etc/letsencrypt:/etc/letsencrypt" -v "/var/lib/letsencrypt:/var/lib/letsencrypt"
            certbot/certbot certonly --standalone --agree-tos
            --email {{ letsencrypt_email }} --no-eff-email -n
            -d {{ domain_name }} -d www.{{ domain_name }}
          args:
            creates: "/etc/letsencrypt/live/{{ domain_name }}"

    - name: ">> 8. Launch Final Application"
      block:
        - name: "Run docker compose up"
          command: "docker compose up -d --build"
          args: { chdir: "{{ project_path }}" }
        - name: "Wait 15s for services to be ready"
          pause: { seconds: 15 }
        - name: "Generate Laravel App Key"
          command: "docker compose exec app php artisan key:generate --force"
          args: { chdir: "{{ project_path }}" }
        - name: "Run Laravel migrations"
          command: "docker compose exec app php artisan migrate --force"
          args: { chdir: "{{ project_path }}" }

    - name: ">> 9. Setup Auto-Renewal for SSL"
      template: { src: templates/certbot-renew.sh.j2, dest: /etc/cron.daily/certbot-renew, mode: '0755' }
